# Generated by Django 3.2.9 on 2021-12-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifftank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CA2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff', models.CharField(max_length=20)),
                ('eff_date', models.CharField(max_length=40)),
                ('change', models.BooleanField()),
                ('sub_chap', models.TextField(blank=True, null=True)),
                ('desc1', models.TextField(blank=True, null=True)),
                ('desc2', models.TextField(blank=True, null=True)),
                ('desc3', models.TextField(blank=True, null=True)),
                ('footnote', models.CharField(blank=True, max_length=10, null=True)),
                ('uom', models.CharField(blank=True, max_length=3, null=True)),
                ('mfn', models.CharField(blank=True, max_length=128, null=True)),
                ('gt', models.CharField(blank=True, max_length=128, null=True)),
                ('aut', models.CharField(blank=True, max_length=128, null=True)),
                ('nzt', models.CharField(blank=True, max_length=128, null=True)),
                ('ccct', models.CharField(blank=True, max_length=128, null=True)),
                ('ldct', models.CharField(blank=True, max_length=128, null=True)),
                ('gpt', models.CharField(blank=True, max_length=128, null=True)),
                ('ust', models.CharField(blank=True, max_length=128, null=True)),
                ('mxt', models.CharField(blank=True, max_length=128, null=True)),
                ('ct', models.CharField(blank=True, max_length=128, null=True)),
                ('ciat', models.CharField(blank=True, max_length=128, null=True)),
                ('crt', models.CharField(blank=True, max_length=128, null=True)),
                ('it', models.CharField(blank=True, max_length=128, null=True)),
                ('nt', models.CharField(blank=True, max_length=128, null=True)),
                ('slt', models.CharField(blank=True, max_length=128, null=True)),
                ('pt', models.CharField(blank=True, max_length=128, null=True)),
                ('colt', models.CharField(blank=True, max_length=128, null=True)),
                ('jt', models.CharField(blank=True, max_length=128, null=True)),
                ('pat', models.CharField(blank=True, max_length=128, null=True)),
                ('hnt', models.CharField(blank=True, max_length=128, null=True)),
                ('kt', models.CharField(blank=True, max_length=128, null=True)),
                ('ceut', models.CharField(blank=True, max_length=128, null=True)),
                ('uat', models.CharField(blank=True, max_length=128, null=True)),
                ('cptpt', models.CharField(blank=True, max_length=128, null=True)),
                ('utk', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
