# Generated by Django 3.2.9 on 2021-12-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifftank', '0002_ca2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=100)),
                ('two', models.CharField(max_length=200)),
            ],
        ),
    ]
