# Generated by Django 3.2.9 on 2021-12-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifftank', '0003_testtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ca2021',
            old_name='kt',
            new_name='krt',
        ),
    ]
