# Generated by Django 3.2.9 on 2021-12-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifftank', '0004_rename_kt_ca2021_krt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ca2021',
            old_name='utk',
            new_name='ukt',
        ),
    ]
