# Generated by Django 3.2.9 on 2021-12-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifftank', '0005_rename_utk_ca2021_ukt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca2021',
            name='change',
            field=models.CharField(max_length=20),
        ),
    ]
